# uncoment with using ecr
# - name: Login to ECR
#   shell: $(aws ecr get-login --no-include-email --region us-east-1)

- name: Kubeadm Reset
  shell: kubeadm reset -f >> reset.log
  args:
    chdir: $HOME
    creates: reset.log

- name: Join the cluster. Use log to prevent joining twice
  shell: "{{ hostvars[groups['tag_Role_master'][0]]['join_command'] }} >> node.log"
  ignore_errors: yes
  args:
    chdir: $HOME
    creates: node.log

- name: Kubelet file
  shell: chmod 777 /var/lib/kubelet/config.yaml
