apiVersion: v1
kind: ReplicationController
metadata:
  name: ping-pong
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: msfidelis/ping-pong:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: ping-pong
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    app: ping-pong  