apiVersion: v1
kind: ReplicationController
metadata:
  name: microapi
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: microapi
    spec:
      containers:
      - name: microapi
        image: msfidelis/micro-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: microapi
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    app: microapi

---

apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: microapi
  namespace: default
spec:
  scaleRef:
    kind: ReplicationController
    name: microapi
    namespace: default
  minReplicas: 5
  maxReplicas: 100
  cpuUtilization:
    targetPercentage: 50