- hosts: tag_Role_master
  become: yes
  tasks:

    - name: update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies packages
      apt:
        name: "{{ packages }}"
        update_cache: true
        state: present
      vars:
        packages:
          - unzip     

    - name: Download package kubernetes-state
      shell: cd /tmp && curl -o kube-state-metrics-1.4.zip https://codeload.github.com/kubernetes/kube-state-metrics/zip/release-1.4

    - name: Unzip release
      shell: cd /tmp && unzip kube-state-metrics-1.4.zip

    - name: Create metrics service
      shell: kubectl apply -f /tmp/kube-state-metrics-release-1.4/kubernetes

    - template:
        src: ./templates/newrelic-k8s.yml
        dest: /tmp/newrelic-k8s.yml
        owner: root
        group: root
        mode: 0775

    - name: Deploy Newrelic Infrastructure Agent
      shell: kubectl apply -f /tmp/newrelic-k8s.yml
